services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: shopping_app_server
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      APP_PORT: 3000
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: nestjs
      DB_PASSWORD: secret
      DB_NAME: shopping_app
      JWT_ACCESS_SECRET: secret
      JWT_ACCESS_EXPIRATION: 1h
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - db
      - cache
    networks:
      - nestjs_shopping_app
  db:
    image: postgres:16
    container_name: shopping_app_db
    environment:
      POSTGRES_DB: shopping_app
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
    networks:
      - nestjs_shopping_app
  cache:
    image: redis:latest
    container_name: shopping_app_cache
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    networks:
      - nestjs_shopping_app

networks:
  nestjs_shopping_app:

volumes:
  db_data:
  cache_data:
